export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const UPDATE_PHONE_SUCCESS = 'UPDATE_PHONE_SUCCESS';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS';
export const CREATE_PHONE_SUCCESS = 'CREATE_PHONE_SUCCESS';

export const SEARCH_RESTAURANT_SUCCESS = 'SEARCH_RESTAURANT_SUCCESS';
export const SELECT_RESTAURANT_SUCCESS = 'SELECT_RESTAURANT_SUCCESS';
export const GET_MENU_SUCCESS = 'SELECT_RESTAURANT_SUCCESS';

export const ADD_ITEM_TO_ORDER = 'ADD_ITEM_TO_ORDER';
export const REMOVE_ITEM_TO_ORDER = 'REMOVE_ITEM_TO_ORDER';
export const ADD_COUNT_ITEM_TO_ORDER = 'ADD_COUNT_ITEM_TO_ORDER';
export const REMOVE_COUNT_ITEM_TO_ORDER = 'REMOVE_COUNT_ITEM_TO_ORDER';
export const GET_RES_DETAILS_SUCCESS = 'GET_RES_DETAILS_SUCCESS';

export const CLEAR_SEARCH_RESTAURANT_RESULT= 'CLEAR_SEARCH_RESTAURANT_RESULT';
export const CLEAR_CURRENT_ORDER= 'CLEAR_CURRENT_ORDER';
export const CLEAR_CURRENT_USER= 'CLEAR_CURRENT_USER';


export const PLACE_ORDER_SUCCESS= 'PLACE_ORDER_SUCCESS';
export const ADD_PRICE_TO_TOTAL_PRICE= 'ADD_PRICE_TO_TOTAL_PRICE';
export const GET_CURRENT_USER_SUCCESS= 'GET_CURRENT_USER_SUCCESS';

export const GET_SIGNUP_RESTAURANT_LIST_FOR_MANAGER_SUCCESS = 'GET_SIGNUP_RESTAURANT_LIST_FOR_MANAGER_SUCCESS';
export const GET_SIGNUP_RESTAURANT_LIST_FOR_OWNER_SUCCESS = 'GET_SIGNUP_RESTAURANT_LIST_FOR_OWNER_SUCCESS';
export const GET_ORDER_DETAILS_BY_SUCCESS = 'GET_ORDER_DETAILS_BY_SUCCESS';


export const GET_RESTAURANT_DETAILS_FOR_MANAGER_SUCCESS = 'GET_RESTAURANT_DETAILS_FOR_MANAGER_SUCCESS';
export const GET_PENDING_ORDERS_FOR_MANAGER_SUCCESS = 'GET_PENDING_ORDERS_FOR_MANAGER_SUCCESS';
export const GET_ALL_ORDERS_FOR_MANAGER_SUCCESS = 'GET_ALL_ORDERS_FOR_MANAGER_SUCCESS';
export const GET_AVAILABLE_DELIVERY_BOYS_SUCCESS = 'GET_AVAILABLE_DELIVERY_BOYS_SUCCESS';
export const ASSIGN_ORDER_TO_DELIVERY_BOY_SUCCESS = 'ASSIGN_ORDER_TO_DELIVERY_BOY_SUCCESS';
export const API_BASE = `http://localhost:8080`;




