export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const UPDATE_PHONE_SUCCESS = 'UPDATE_PHONE_SUCCESS';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS';
export const CREATE_PHONE_SUCCESS = 'CREATE_PHONE_SUCCESS';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_PHONE_SUCCESS = 'DELETE_PHONE_SUCCESS';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';

export const SEARCH_RESTAURANT_SUCCESS = 'SEARCH_RESTAURANT_SUCCESS';
export const SELECT_RESTAURANT_SUCCESS = 'SELECT_RESTAURANT_SUCCESS';
export const GET_MENU_SUCCESS = 'SELECT_RESTAURANT_SUCCESS';

export const ADD_ITEM_TO_ORDER = 'ADD_ITEM_TO_ORDER';
export const REMOVE_ITEM_TO_ORDER = 'REMOVE_ITEM_TO_ORDER';
export const ADD_COUNT_ITEM_TO_ORDER = 'ADD_COUNT_ITEM_TO_ORDER';
export const REMOVE_COUNT_ITEM_TO_ORDER = 'REMOVE_COUNT_ITEM_TO_ORDER';
export const GET_RES_DETAILS_SUCCESS = 'GET_RES_DETAILS_SUCCESS';

export const CLEAR_SEARCH_RESTAURANT_RESULT= 'CLEAR_SEARCH_RESTAURANT_RESULT';
export const CLEAR_CURRENT_ORDER= 'CLEAR_CURRENT_ORDER';
export const CLEAR_CURRENT_USER= 'CLEAR_CURRENT_USER';


export const PLACE_ORDER_SUCCESS= 'PLACE_ORDER_SUCCESS';
export const ADD_PRICE_TO_TOTAL_PRICE= 'ADD_PRICE_TO_TOTAL_PRICE';
export const GET_CURRENT_USER_SUCCESS= 'GET_CURRENT_USER_SUCCESS';

export const GET_SIGNUP_RESTAURANT_LIST_FOR_MANAGER_SUCCESS = 'GET_SIGNUP_RESTAURANT_LIST_FOR_MANAGER_SUCCESS';
export const GET_SIGNUP_RESTAURANT_LIST_FOR_OWNER_SUCCESS = 'GET_SIGNUP_RESTAURANT_LIST_FOR_OWNER_SUCCESS';
export const GET_ORDER_DETAILS_BY_ID_SUCCESS = 'GET_ORDER_DETAILS_BY_ID_SUCCESS';
export const GET_DELIVERY_BOY_ASSIGNED_ORDER_SUCCESS = 'GET_DELIVERY_BOY_ASSIGNED_ORDER_SUCCESS';
export const MARK_ORDER_AS_DELIVERED_SUCCESS = 'MARK_ORDER_AS_DELIVERED_SUCCESS';
export const GET_ORDERED_ASSIGNED_TO_ME_SUCCESS = 'GET_ORDERED_ASSIGNED_TO_ME_SUCCESS';

export const GET_RESTAURANT_DETAILS_FOR_MANAGER_SUCCESS = 'GET_RESTAURANT_DETAILS_FOR_MANAGER_SUCCESS';
export const GET_PENDING_ORDERS_FOR_MANAGER_SUCCESS = 'GET_PENDING_ORDERS_FOR_MANAGER_SUCCESS';
export const GET_ALL_ORDERS_FOR_MANAGER_SUCCESS = 'GET_ALL_ORDERS_FOR_MANAGER_SUCCESS';
export const GET_AVAILABLE_DELIVERY_BOYS_SUCCESS = 'GET_AVAILABLE_DELIVERY_BOYS_SUCCESS';
export const ASSIGN_ORDER_TO_DELIVERY_BOY_SUCCESS = 'ASSIGN_ORDER_TO_DELIVERY_BOY_SUCCESS';


// ADMIN functionalities

export const ADMIN_GET_PENDING_APPROVALS_SUCCESS = 'ADMIN_GET_PENDING_APPROVALS_SUCCESS';
export const ADMIN_GET_ALL_USERS_SUCCESS = 'ADMIN_GET_ALL_USERS_SUCCESS';
export const ADMIN_GET_ALL_RESTAURANTS_SUCCESS = 'ADMIN_GET_ALL_RESTAURANTS_SUCCESS';
export const ADMIN_DELETE_USER_SUCCESS = 'ADMIN_DELETE_USER_SUCCESS';



export const ADMIN_GET_SELECTED_USER_DETAILS_SUCCESS = 'ADMIN_GET_SELECTED_USER_DETAILS_SUCCESS';

export const ADMIN_CREATE_USER_ADDRESS_SUCCESS = 'ADMIN_CREATE_USER_ADDRESS_SUCCESS';
export const ADMIN_UPDATE_USER_ADDRESS_SUCCESS = 'ADMIN_UPDATE_USER_ADDRESS_SUCCESS';
export const ADMIN_DELETE_USER_ADDRESS_SUCCESS = 'ADMIN_DELETE_USER_ADDRESS_SUCCESS';
export const ADMIN_CREATE_USER_PHONE_SUCCESS = 'ADMIN_CREATE_USER_PHONE_SUCCESS';
export const ADMIN_UPDATE_USER_PHONE_SUCCESS = 'ADMIN_UPDATE_USER_PHONE_SUCCESS';
export const ADMIN_DELETE_USER_PHONE_SUCCESS = 'ADMIN_DELETE_USER_PHONE_SUCCESS';
export const ADMIN_UPDATE_USER_PROFILE_SUCCESS = 'ADMIN_UPDATE_USER_PROFILE_SUCCESS';


export const CREATE_MENU_ITEM_SUCCESS = 'CREATE_MENU_ITEM_SUCCESS';
export const UPDATE_MENU_ITEM_SUCCESS= 'UPDATE_MENU_ITEM_SUCCESS';
export const DELETE_MENU_ITEM_SUCCESS = 'DELETE_MENU_ITEM_SUCCESS';
export const DELETE_RESTAURANT_SUCCESS = 'DELETE_RESTAURANT_SUCCESS';


export const APPROVE_OWNERSHIP_SUCCESS = 'APPROVE_OWNERSHIP_SUCCESS';
export const REJECT_OWNERSHIP_SUCCESS = 'REJECT_OWNERSHIP_SUCCESS';
export const GET_OWNER_RESTAURANT_SUCCESS = 'GET_OWNER_RESTAURANT_SUCCESS';

export const REQUEST_OWNERSHIP_SUCCESS = 'REQUEST_OWNERSHIP_SUCCESS';
export const UNASSIGN_OWNERSHIP_SUCCESS = 'UNASSIGN_OWNERSHIP_SUCCESS';
export const UNOWNED_RESTAURANT_SUCCESS = 'UNOWNED_RESTAURANT_SUCCESS';



export const API_BASE = `http://localhost:8080`;




