export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_SUCCESS = 'LOGIN_SUCCESS';

export const SEARCH_RESTAURANT_SUCCESS = 'SEARCH_RESTAURANT_SUCCESS';
export const SELECT_RESTAURANT_SUCCESS = 'SELECT_RESTAURANT_SUCCESS';
export const GET_MENU_SUCCESS = 'SELECT_RESTAURANT_SUCCESS';

export const ADD_ITEM_TO_ORDER = 'ADD_ITEM_TO_ORDER';
export const REMOVE_ITEM_TO_ORDER = 'REMOVE_ITEM_TO_ORDER';
export const ADD_COUNT_ITEM_TO_ORDER = 'ADD_COUNT_ITEM_TO_ORDER';
export const REMOVE_COUNT_ITEM_TO_ORDER = 'REMOVE_COUNT_ITEM_TO_ORDER';
export const GET_RES_DETAILS_SUCCESS = 'GET_RES_DETAILS_SUCCESS';




